### PR TITLE
Fixed #10

### LINKED ISSUE #10: No implementation of MockStorageReference.getDownloadURL
I've gone ahead and forked this repo and [implemented `getDownloadURL` within `MockStorageReference`](https://github.com/ChopinDavid/firebase_storage_mocks/commit/c228e8a4b29ac9b6ba91571223f7705e0c45cb06). It seems that there is no way, AFAIK, to construct a download url that is similar to an actual Firebase Storage download URL (`https://firebasestorage.googleapis.com/v0/b/{your-application}.appspot.com/o/{url-encoded-path-name}?alt=media&token={your-token}`) so I have it returning a dummy value instead (`https://firebasestorage.googleapis.com/{path}`). This dummy value could be updated so that `_path` is url encoded when interpolated into the download URL path that the function returns. Also, there could probably also be a test written around this, but I didn't see any Mock Reference tests.

Let me know if you are interested in me creating a PR for my fork.

### PR DESCRIPTION
**Pull request by OlegNovosad**
Fixed #10: Added better path handling. Made download url return the full path to the file.

### CODE REVIEW

**Comment by OlegNovosad** [comment]
The `_path` was incorrectly building itself so I've added the `/` to the each child end. Having this in place also results in the file being put having extra `/` which should be dropped for `getDownloadUrl` implementation.

**Comment by cedvdb** [comment]
@atn832 can you merge this ?

**Comment by cedvdb** [comment]
It would be better if the download URL was a valid image url. So integrations test don't have a 404 and look nicer when running in front of an audience.

**Comment by atn832** [comment]
Thanks for the PR @OlegNovosad. Sorry for the delay. Someone has since reimplemented it in #17 along with unit tests, so I've gone ahead and merged theirs instead. Feel free to contribute other PRs, and I'll make sure I respond faster next time.

**Pull request closed without merging**
